# Start from a core stack version
FROM python:3.11-slim-buster

# Docker remains within this directory in the container
WORKDIR /workspace

# Copy requirements.txt to the docker container
COPY requirements.txt ./requirements.txt

# Update pip
RUN pip3 install --upgrade pip

# Install python dependencies
RUN pip3 install --no-cache-dir -r requirements.txt

# Expose port 
EXPOSE 8501

# Run the command to start the app
CMD ["streamlit", "run", "app.py"]
